// 2021-11-29-vue/todolist/src/components/TodoItem.vue
<template>
  <li>
    {{ todo.completed ? "DONE: " : "TODO: " }}
    {{ todo.title }}
    <v-btn @click="$emit('toggle', todo.id)" color="secondary">toggle</v-btn>
    <v-btn @click="$emit('delete', todo.id)" color="secondary">delete</v-btn>
  </li>
</template>

<script>
export default {
  name: "TodoItem",
  props: ["todo"],
  // events: ["toggle", "delete"],
};
</script>

<style scoped></style>

// react-ts/course-2019-03-13/todolist/src/TodoItem.tsx
import React, {memo} from 'react';
import TodoType from './TodoType';

import './TodoItem.css';

type TodoItemProps = {
  todo: TodoType;
  onCompleted: () => void;
};

const TodoItem = (props: TodoItemProps) => {
  return (
    <div
      className={props.todo.completed ? 'todo completed' : 'todo'}
      onClick={() => {
        props.onCompleted();
      }}
    >
      {props.todo.completed ? 'DONE:' : 'TODO:'} {props.todo.title}
    </div>
  );
};

export default memo(TodoItem);
