// 2021-11-29-vue/todolist/src/components/TodoItem.vue
<template>
  <li>
    {{ todo.completed ? "DONE: " : "TODO: " }}
    {{ todo.title }}
    <v-btn @click="$emit('toggle', todo.id)" color="secondary">toggle</v-btn>
    <v-btn @click="$emit('delete', todo.id)" color="secondary">delete</v-btn>
  </li>
</template>

<script>
export default {
  name: "TodoItem",
  props: ["todo"],
  // events: ["toggle", "delete"],
};
</script>

<style scoped></style>

// react-ts/course-2020-02-03/todolist/src/TodoItem.tsx
import styles from "./TodoItem.module.css";
import React from "react";

type TodoItemProps = {
  title: string;
  completed: boolean;
  onToggle: () => void;
};

const TodoItem = (props: TodoItemProps) => {
  const completed = props.completed;
  return (
    <li
      d-completed={completed ? "true" : "false"}
      onClick={() => {
        props.onToggle();
      }}
      className={styles.todoitem}
    >
      {completed ? "DONE" : "TODO"}: {props.title}
    </li>
  );
};

export default TodoItem;
