// 2021-04-12-react-power-workshop/todolist/src/TodoItem.tsx
type TodoItemProps = {
  title: string;
  completed: boolean;
  onCompletedChange: (completed: boolean) => void;
  onDelete: () => void;
};

function TodoItem(props: TodoItemProps) {
  return (
    <li>
      <input
        type="checkbox"
        checked={props.completed}
        onChange={(event) => {
          props.onCompletedChange(event.target.checked);
        }}
      />
      {props.completed ? "DONE: " : "TODO: "}
      {props.title}
      <button onClick={() => props.onDelete()}>delete</button>
    </li>
  );
}

export default TodoItem;

// 2021-11-29-vue/todolist/src/components/TodoItem.vue
<template>
  <li>
    {{ todo.completed ? "DONE: " : "TODO: " }}
    {{ todo.title }}
    <v-btn @click="$emit('toggle', todo.id)" color="secondary">toggle</v-btn>
    <v-btn @click="$emit('delete', todo.id)" color="secondary">delete</v-btn>
  </li>
</template>

<script>
export default {
  name: "TodoItem",
  props: ["todo"],
  // events: ["toggle", "delete"],
};
</script>

<style scoped></style>
